### ISSUE TITLE
Large image file size

### ISSUE THREAD

**Issue by le000255** [le000255/Picture-This#1]
@abhaysharma Hello Abhay!
I notice that images generated by https://derivv.com/ have large file size (~7MB for the largest image). Is it the expected behaviour? Do I need to optimize the files' size in any way?

Thank you for your time!
Eddie

**Comment by abhaysharma** [comment]
@le000255 I will accept the large file sizes for this assignment.

**Comment by le000255** [comment]
Thank you so much, Abhay!
